---
name: coverage

on:
  push:
    paths:
      - "**.rs"

jobs:
  test:
    name: Generate Coverage Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Cache
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2
      - name: Install cargo-hack
        uses: taiki-e/install-action@05515455a9007c7c6f0b215637566ab8e9872c12 # v2
        with:
          tool: cargo-tarpaulin
      - name: Generate code coverage
        run: |
          cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
