---
name: release-github

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-rc*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Create Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2
        with:
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
