---
name: release-github

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-rc*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Create Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2
        with:
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
